services:
  nginx:
    depends_on:
      - app
    image: nginx:alpine
    container_name: web-sem1.nginx
    tty: true
    ports:
      - "81:80"
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/app
    networks:
      - seminario1
  db:
    image: postgres
    container_name: web-sem1.db
    tty: true
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - seminario1
  app:
    depends_on:
      - db
    build:
      context: .
    image: ifcvda/web-sem1
    container_name: web-sem1.app
    tty: true
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app
    networks:
      - seminario1
volumes:
  db:
    driver: local
networks:
  seminario1:
    driver: bridge